### ISSUE TITLE
I feel offended

### ISSUE THREAD

**Issue by Zethson** [chahuistle/chahuistle.github.io#1]

**Comment by chahuistle** [comment]
me too, thanks

**Comment by Zethson** [comment]
There's no cure.

**Comment by subwaystation** [comment]
What took you so long. @chahuistle ?

**Comment by chahuistle** [comment]
Fizz was easy. Buzz was very complex. But FizzBuzz was harder than making this glorious diagram:

![image](https://user-images.githubusercontent.com/1537189/57406078-3127b200-719d-11e9-894a-fee00042985a.png)

**Comment by Zethson** [comment]
![image](https://user-images.githubusercontent.com/21954664/57406261-994bb780-71e0-11e9-8e19-2e3788bc5bed.png)

**Comment by Zethson** [comment]
Ma boiii

**Comment by chahuistle** [comment]
> ma boiii
https://www.youtube.com/watch?v=1JjpHmt7J8g

**Comment by subwaystation** [comment]
My man!

https://www.youtube.com/watch?v=QJt--ppS9AA
