### ISSUE TITLE
Döner

### ISSUE THREAD

**Issue by Zethson** [chahuistle/chahuistle.github.io#3]
Meine Liebe zu Döner begann vor acht Jahren. Mit fünf ging ich zum ersten Mal zu einem Dönerstand und holte mir einen saftigen Döner mit Salat und Soße. Er schmeckte so heftig. Ich sagte meiner Mutter, dass sie mir noch einen holen soll, aber sie wollte mir keinen Döner kaufen. Die ganze Nacht dachte ich an den Döner. Nach circa vier Jahren war ich immer noch dönersüchtig. Ich hab damals sicher jede Woche einen Döner gegessen. Tu ich eigentlich immer noch, aber ja. Ich möchte an dieser Stelle allen Eltern etwas mitteilen: Verbietet euren Kindern nicht den Döner! Denn ohne Döner existiert keine LIEBE! Und an alle Veganer: Bevor ihr da etwas dahinredet probiert mal Döner, dann können wir mal weiterreden! Man kann Kindern den Döner nicht verbieten. Ihr müsst auch nicht immer bei dem coolsten oder beim luxuriösesten Dönerstand essen - auch bei kleinen Dönerständen kann der Döner heftig schmecken. Aber Qualität hat ihren Preis: Nehmt ruhig den Döner, der 50 Cent mehr kostet — billig heißt nicht immer gut. Und esst euren Döner immer bei einem Türken, Vertraut mir einfach! Ich habe eigentlich vor, mal Bautechnik zu lernen — wenn das nicht klappt, ist mein Plan B Dönerbudenbesitzer zu werden. Ich schwöre euch, Ali's Döner wird der beste Döner Wiens. Und noch ein kleiner Tipp von Ali, ein echter Döner besteht aus: Hühner/Kalb Fleisch, Salat, Soße, scharf

**Comment by Zethson** [comment]
Sende Döner

**Comment by subwaystation** [comment]
Döner macht Schöner.

![image](https://user-images.githubusercontent.com/10184961/57407196-e6308d80-71e2-11e9-9fba-65a4bb0b231e.png)

**Comment by chahuistle** [comment]
wow... that escalated quickly
